### PR TITLE
[OPS-7193][OPS-7190] Bump date_ical to avoid a constructor error.

### PR DESCRIPTION
**Pull request by cafuego**
Also needs an icacreator library bump, see https://www.drupal.org/project/date_ical/issues/2707373

After dev deploy, double check that the lowercase path for the library does not break its
detection. I am not able to make composer install it to the sNakecase
directory name, where it used to live.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
@cafuego  I merged this to test it on dev, but I'm not sure it's there - I tried locally and the library was missing - I added it via a git clone, before I realized it's added in the PR as a submodule, so it seems to work but the repo is ignoring it. Do we want to use submodules here? I don't think any of the others are. (Also, the other libraries aren't handled via composer, as far as I can tell.)

To test, I tried the iCal export on https://dev.humanitarianresponse-info.ahconu.org/en/operations/iraq/events, but it doesn't seem to do anything.

**Comment by cafuego** [comment]
It looks like git had helpfully added the library as submodule when I added the directory and didn't read the warning when I committed the change. Have removed it and added the forked library as plain old library (no composer) in the latest change, which is now deployed on dev and contains the library.

**Comment by lazysoundsystem** [comment]
Thanks for that - I'm still trying to get a reaction from the iCal export on https://dev.humanitarianresponse-info.ahconu.org/en/operations/iraq/events but it doesn't seem to do anything, nor leave any message in the logs. Am I testing the right thing?

**Comment by cafuego** [comment]
I get a VCALENDAR with two events; Ninewa PWG and Erbil Protection Working Group when I hit the iCal link on dev Iraq.

**Comment by lazysoundsystem** [comment]
Thanks for checking - trying in other browsers, I discovered that it's because I don't have software installed to handle .ics...

**Comment by emmajane** [comment]
PS @lazysoundsystem submodules are never the right answer. It's always correct to question their use. Loudly. :)

**Comment by cafuego** [comment]
> Thanks for checking - trying in other browsers, I discovered that it's because I don't have software installed to handle .ics...

wget. always test with wget and *also* check the headers :-)

**Pull request merged**
