### PR TITLE
Complete HRINFO-1012 deployment

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Again, this seems to be pulling in many changes that have long been part of the master branch. For reference: https://humanitarian.atlassian.net/browse/OPS-6856

This brings the drush job for the previous deployment into an update hook as there are very few remaining contacts to be transferred, and we want to do it in a single deploy.

There's also a fix for the HRINFO-1019 fix, which has already been merged to master, which is the source of the conflict.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Closing as the travis ci check won't complete and *may*(?) be holding up the check on https://github.com/UN-OCHA/hrinfo-site/pull/968 - will re-open when/if that completes

**Comment by lazysoundsystem** [comment]
The other completed (had to add another commit to restart the travis job). Starting this again now dev's just been updated from master...

**Comment by lazysoundsystem** [comment]
@attiks - sorry this is late for the review - the deployment is due at 10am tomorrow morning, but I spent much of this afternoon struggling because I didn't realise I could 'Create a merge commit' on this repo, hence all the history going back to February.

Most of the changes to production have already been merged in https://github.com/UN-OCHA/hrinfo-site/pull/959/files - this commit takes the code from the hr_events drush command and puts it in an update hook, so it won't repeat the changes already made.

To see what will change on production, the current tag is https://github.com/UN-OCHA/hrinfo-site/tree/2020-10-20-part-1 - it's all been tested by Marina and Tomaz on staging, but as Emma pointed out, it should really have a dev review too.

There's also a fix for a faulty fix introduced in https://github.com/UN-OCHA/hrinfo-site/pull/955/files#diff-fac6cbb730ddac9af11357dc1cd533701c90d0c728776115a0a2b299e3d5d168. It's minor, but it was causing a lot of noise in the logs.

**Review by attiks — APPROVED** [review]
Looks solid to me

**Pull request merged**
